#!/usr/bin/env bash
# Build OUTPUT_EXCERPTS_20260929.md: a pointer-and-clip index for the large
# intermediates that are NOT committed, plus the key tables from the outputs
# that are. Every clip is cut from the real file at generation time.
set -uo pipefail
ROOT="$HOME/system_development"
OUT="$ROOT/OUTPUT_EXCERPTS_20260929.md"
P2="$ROOT/phase2b_charge_design"
exec > "$OUT"

echo "# Output excerpts and large-file index - 29 September 2026"
echo
echo "Generated by \`make_excerpts.sh\` on $(date -Iseconds) on $(hostname)."
echo "Every clip below is cut from the file named above it at generation time."
echo "Paths are relative to \`~/system_development\` on hpc1."
echo

clip () {  # clip <path> <lines> <description>
  local p="$1" n="$2" d="$3"
  echo "### \`${p#$ROOT/}\`"
  echo
  if [[ ! -f "$p" ]]; then echo "**ABSENT at generation time.**"; echo; return; fi
  echo "$d  "
  echo "size $(stat -c %s "$p") bytes, $(wc -l < "$p") lines, modified $(date -r "$p" -Iseconds)  "
  echo "md5 \`$(md5sum "$p" | cut -d' ' -f1)\`"
  echo
  echo '```'
  head -n "$n" "$p"
  echo '```'
  echo
}

echo "## 1. Committed outputs - key tables"
echo
echo "These files are in the repository in full. The clips are for orientation."
echo
clip "$P2/02_singlepoints/refstate_diagnostic.pbs.out" 60 \
  "Reference-state diagnostic: 2 basis sets x 3 environments x 2 geometries."
clip "$P2/06b_inner_shell/s6b_inner_shell.pbs.out" 80 \
  "Inner-shell charge test: parent plus three constructed points at decreasing standoff."
clip "$P2/06_charge_tests/s6_charge_tests.pbs.out" 45 \
  "Original charge test on the production shells 3.0, 4.0, 5.0."
clip "$P2/08_frame_sensitivity/s9_frame_sensitivity.pbs.out" 90 \
  "Test B6, frame sensitivity of the difference potential over ten frames."
clip "$P2/06b_inner_shell/sites.tsv" 10 \
  "Constructed inner points. NOTE: the shell column is in a REACTANT-ONLY standoff convention, not the union-envelope convention of the production grid. Compare by distance to the ether oxygen, not by shell name."
clip "$P2/08_frame_sensitivity/dv_grid_ensemble_mean.tsv" 12 \
  "Ensemble mean difference potential over ten frames, per site, with its standard deviation."
clip "$ROOT/05_qmmm/19_ensemble_barriers/ensemble_barriers.tsv" 18 \
  "The barrier ensemble."
clip "$ROOT/05_qmmm/PROVENANCE.log" 200 \
  "Every script change made on hpc1, with its reason."

echo "## 2. Large intermediates NOT committed"
echo
echo "These are regenerable from the committed scripts and the geometries."
echo "They are indexed here by size and checksum, following the convention of"
echo "\`CHECKSUMS_large_files.txt\`. A format sample is given for each kind so a"
echo "reader can tell what the file contains without having it."
echo
for d in "$P2/08_frame_sensitivity" "$P2/06b_inner_shell" "$P2/06_charge_tests"; do
  [[ -d "$d" ]] || continue
  echo "### \`${d#$ROOT/}\`"
  echo
  echo "| pattern | files | total MB |"
  echo "|---|---|---|"
  for pat in 'sp_*.gbw' 'sp_*.densities' 'sp_*.out' 'vpot_*.out' 'sp_*.cpcm' '*.tmp' 'pc_*.pc'; do
    n=$(find "$d" -maxdepth 1 -name "$pat" 2>/dev/null | wc -l)
    [[ "$n" -eq 0 ]] && continue
    mb=$(find "$d" -maxdepth 1 -name "$pat" -printf '%s\n' 2>/dev/null | awk '{s+=$1} END{printf "%.1f", s/1048576}')
    echo "| \`$pat\` | $n | $mb |"
  done
  echo
done

echo "### format samples"
echo
for f in "$P2/08_frame_sensitivity/vpot_02450_R.out" \
         "$P2/08_frame_sensitivity/row_order.tsv" \
         "$P2/06b_inner_shell/pc_inner_1.5_p.pc"; do
  [[ -f "$f" ]] || continue
  echo "\`${f#$ROOT/}\` - first 4 lines"
  echo '```'
  head -4 "$f"
  echo '```'
  echo
done

echo "### checksums of the excluded files"
echo
echo '```'
for d in "$P2/08_frame_sensitivity" "$P2/06b_inner_shell"; do
  [[ -d "$d" ]] || continue
  find "$d" -maxdepth 1 \( -name 'vpot_*.out' -o -name 'sp_*.gbw' \) -print0 2>/dev/null \
    | sort -z | xargs -0 -r md5sum 2>/dev/null | sed "s|$ROOT/||"
done
echo '```'
